-- we don't know how to generate root <with-no-name> (class Root) :(

comment on database postgres is 'default administrative connection database';

create table departments
(
    department_code    varchar(20)  not null
        primary key,
    department_name    varchar(100) not null
        unique,
    head_of_department varchar(100)
);

alter table departments
    owner to postgres;

create table students
(
    id              serial
        primary key,
    first_name      varchar(50) not null,
    last_name       varchar(50) not null,
    semester        varchar(10),
    department_code varchar(20)
        constraint fk_department_code
            references departments
);

alter table students
    owner to postgres;

create table courses
(
    course_code            varchar(20)   not null
        primary key,
    course_name            varchar(100)  not null,
    credits                numeric(3, 1) not null,
    prerequisites          varchar(255),
    is_active              boolean default true,
    major_code             varchar(20)
        constraint fk_course_department_code
            references departments,
    available_for_semester varchar(50),
    instructor             varchar(100)
);

alter table courses
    owner to postgres;

create table instructors
(
    instructor_id serial
        primary key,
    first_name    varchar(100) not null,
    last_name     varchar(100) not null,
    email         varchar(100)
        unique
);

alter table instructors
    owner to postgres;

create table sections
(
    section_id         serial
        primary key,
    course_code        varchar(20) not null
        references courses,
    semester           varchar(20) not null,
    year               integer     not null,
    instructor_id      integer
        references instructors,
    capacity           integer     not null,
    current_enrollment integer     default 0,
    status             varchar(20) default 'Open'::character varying
);

alter table sections
    owner to postgres;

create table enrollment
(
    enrollement_id  serial
        primary key,
    student_id      integer not null
        references students,
    section_id      integer not null
        references sections
            on update cascade,
    grade           varchar(5),
    status          varchar(20) default 'current'::character varying,
    enrollment_id   integer generated by default as identity,
    enrollment_date timestamp(6),
    unique (student_id, section_id)
);

alter table enrollment
    owner to postgres;

